version: '3.8'
services:

#------------------------ mongodb ---------------------------

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    command: [--auth]
    volumes:
      - '~\Documents\Dev\MongoDb:/data/db'
    ports:
      - 27017:27017
    restart: unless-stopped

#------------------------ My SQL ---------------------------
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
#      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - '~\Documents\Dev\MySQL:/var/lib/mysql'

 